const PLAN_CONFIGS = {
  FREE_TRIAL: {
    plan: "FREE_TRIAL",
    status: "TRIALING",
    price: 0,
    maxEmployees: 10,
    maxBranches: 1,
    trialDays: 14,
    hasGeofence: true,
    hasPayroll: true,
    hasShiftPlanner: true,
    hasApiAccess: false,
  },
  STARTER: {
    plan: "STARTER",
    status: "ACTIVE",
    price: 2499,
    maxEmployees: 25,
    maxBranches: 2,
    periodDays: 30,
    hasGeofence: true,
    hasPayroll: true,
    hasShiftPlanner: true,
    hasApiAccess: false,
  },
  PROFESSIONAL: {
    plan: "PROFESSIONAL",
    status: "ACTIVE",
    price: 6999,
    maxEmployees: 100,
    maxBranches: 10,
    periodDays: 30,
    hasGeofence: true,
    hasPayroll: true,
    hasShiftPlanner: true,
    hasApiAccess: true,
  },
  ENTERPRISE: {
    plan: "ENTERPRISE",
    status: "ACTIVE",
    price: 16999,
    maxEmployees: 1000,
    maxBranches: 50,
    periodDays: 30,
    hasGeofence: true,
    hasPayroll: true,
    hasShiftPlanner: true,
    hasApiAccess: true,
  },
};

module.exports = { PLAN_CONFIGS };
